/*
 * What each notification provider needs entered.
 *
 * GENERATED by extra/generate-notification-fields.js from the interface's own
 * forms, which are the only authoritative description of a provider's
 * settings. Do not edit by hand: run the generator instead, and a test will
 * tell you if this file and the forms have come apart.
 *
 * A provider absent from here has no form component, so nothing is known about
 * what it needs. That is reported as the absence of a description rather than
 * as needing nothing, so a client can ask for its settings directly instead of
 * offering an empty form.
 */
const NOTIFICATION_FIELDS = {
    "Whatsapp360messenger": [
        {
            "key": "Whatsapp360messengerAuthToken",
            "label": "360messenger API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "Whatsapp360messengerRecipient",
            "label": "Recipient phone number(s)",
            "type": "text",
            "required": false
        },
        {
            "key": "Whatsapp360messengerUseTemplate",
            "label": "Custom message template",
            "type": "boolean",
            "required": false
        }
    ],
    "Elks": [
        {
            "key": "elksUsername",
            "label": "Username",
            "type": "text",
            "required": true
        },
        {
            "key": "elksAuthToken",
            "label": "Password",
            "type": "secret",
            "required": true
        },
        {
            "key": "elksFromNumber",
            "label": "From",
            "type": "text",
            "required": true
        },
        {
            "key": "elksToNumber",
            "label": "To Number",
            "type": "text",
            "required": true
        }
    ],
    "AlertNow": [
        {
            "key": "alertNowWebhookURL",
            "label": "Webhook URL",
            "type": "text",
            "required": true
        }
    ],
    "alerta": [
        {
            "key": "alertaApiEndpoint",
            "label": "API Endpoint",
            "type": "text",
            "required": true
        },
        {
            "key": "alertaEnvironment",
            "label": "Environment",
            "type": "text",
            "required": true
        },
        {
            "key": "alertaApiKey",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "alertaAlertState",
            "label": "Alert State",
            "type": "text",
            "required": true
        },
        {
            "key": "alertaRecoverState",
            "label": "Recover State",
            "type": "text",
            "required": true
        }
    ],
    "apprise": [
        {
            "key": "appriseURL",
            "label": "Apprise URL",
            "type": "text",
            "required": true
        },
        {
            "key": "title",
            "label": "Title",
            "type": "text",
            "required": false
        }
    ],
    "bale": [
        {
            "key": "baleBotToken",
            "label": "Bot Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "baleChatID",
            "label": "Chat ID",
            "type": "text",
            "required": true
        }
    ],
    "Bark": [
        {
            "key": "apiVersion",
            "label": "Bark API Version",
            "type": "select",
            "required": true,
            "options": [
                "v1",
                "v2"
            ]
        },
        {
            "key": "barkEndpoint",
            "label": "Bark Endpoint",
            "type": "text",
            "required": true
        },
        {
            "key": "barkGroup",
            "label": "Bark Group",
            "type": "text",
            "required": true
        },
        {
            "key": "barkSound",
            "label": "Bark Sound",
            "type": "select",
            "required": true,
            "options": [
                "alarm",
                "anticipate",
                "bell",
                "birdsong",
                "bloom",
                "calypso",
                "chime",
                "choo",
                "descent",
                "electronic",
                "fanfare",
                "glass",
                "gotosleep",
                "healthnotification",
                "horn",
                "ladder",
                "mailsent",
                "minuet",
                "multiwayinvitation",
                "newmail",
                "newsflash",
                "noir",
                "paymentsuccess",
                "shake",
                "sherwoodforest",
                "silence",
                "spell",
                "suspense",
                "telegraph",
                "tiptoes",
                "typewriters",
                "update"
            ]
        }
    ],
    "bearsms": [
        {
            "key": "bearsmsUsername",
            "label": "here",
            "type": "text",
            "required": true
        },
        {
            "key": "bearsmsHashKey",
            "label": "Hash Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "bearsmsSenderId",
            "label": "From Name/Number",
            "type": "text",
            "required": false
        },
        {
            "key": "bearsmsPhoneNumber",
            "label": "Recipient Number",
            "type": "text",
            "required": true
        }
    ],
    "Bitrix24": [
        {
            "key": "bitrix24WebhookURL",
            "label": "Bitrix24 Webhook URL",
            "type": "secret",
            "required": true
        },
        {
            "key": "bitrix24UserID",
            "label": "User ID",
            "type": "text",
            "required": true
        }
    ],
    "Brevo": [
        {
            "key": "brevoApiKey",
            "label": "Brevo API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "brevoFromEmail",
            "label": "From Email",
            "type": "text",
            "required": true
        },
        {
            "key": "brevoFromName",
            "label": "From Name",
            "type": "text",
            "required": false
        },
        {
            "key": "brevoToEmail",
            "label": "To Email",
            "type": "text",
            "required": true
        },
        {
            "key": "brevoCcEmail",
            "label": "CC Email",
            "type": "text",
            "required": false
        },
        {
            "key": "brevoBccEmail",
            "label": "BCC Email",
            "type": "text",
            "required": false
        },
        {
            "key": "brevoSubject",
            "label": "Subject",
            "type": "text",
            "required": false
        }
    ],
    "Cellsynt": [
        {
            "key": "cellsyntLogin",
            "label": "Username",
            "type": "text",
            "required": true
        },
        {
            "key": "cellsyntPassword",
            "label": "Password",
            "type": "secret",
            "required": true
        },
        {
            "key": "cellsyntOriginatortype",
            "label": "Originator type",
            "type": "select",
            "required": true,
            "options": [
                "alpha",
                "numeric"
            ]
        },
        {
            "key": "cellsyntOriginator",
            "label": "max 15 digits",
            "type": "text",
            "required": true
        },
        {
            "key": "cellsyntDestination",
            "label": "Destination",
            "type": "text",
            "required": true
        },
        {
            "key": "cellsyntAllowLongSMS",
            "label": "Allow Long SMS",
            "type": "boolean",
            "required": false
        }
    ],
    "clicksendsms": [
        {
            "key": "clicksendsmsLogin",
            "label": "here",
            "type": "text",
            "required": true
        },
        {
            "key": "clicksendsmsPassword",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "clicksendsmsToNumber",
            "label": "Recipient Number",
            "type": "text",
            "required": true
        },
        {
            "key": "clicksendsmsSenderName",
            "label": "Read more",
            "type": "text",
            "required": false
        }
    ],
    "ClickUp": [
        {
            "key": "clickupToken",
            "label": "ClickUp API Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "clickupWorkspaceId",
            "label": "ClickUp Workspace ID",
            "type": "text",
            "required": true
        },
        {
            "key": "clickupChannelId",
            "label": "ClickUp Channel ID",
            "type": "text",
            "required": true
        },
        {
            "key": "clickupDisableUrl",
            "label": "Disable URL in Notification",
            "type": "boolean",
            "required": false
        }
    ],
    "DingDing": [
        {
            "key": "webHookUrl",
            "label": "WebHookUrl",
            "type": "text",
            "required": true
        },
        {
            "key": "secretKey",
            "label": "SecretKey",
            "type": "secret",
            "required": true
        },
        {
            "key": "mentioning",
            "label": "Mentioning",
            "type": "select",
            "required": true,
            "options": [
                "nobody",
                "everyone",
                "specify-mobiles",
                "specify-users"
            ]
        }
    ],
    "discord": [
        {
            "key": "discordWebhookUrl",
            "label": "Discord Webhook URL",
            "type": "secret",
            "required": true
        },
        {
            "key": "discordUsername",
            "label": "Bot Display Name",
            "type": "text",
            "required": false
        },
        {
            "key": "discordPrefixMessage",
            "label": "Prefix Custom Message",
            "type": "text",
            "required": false
        },
        {
            "key": "discordMessageFormat",
            "label": "Message Format",
            "type": "select",
            "required": false,
            "options": [
                "normal",
                "minimalist",
                "custom"
            ]
        },
        {
            "key": "discordChannelType",
            "label": "Select message type",
            "type": "select",
            "required": false,
            "options": [
                "channel",
                "createNewForumPost",
                "postToThread"
            ]
        },
        {
            "key": "postName",
            "label": "Forum post name",
            "type": "text",
            "required": false
        },
        {
            "key": "threadId",
            "label": "Thread / Forum post ID",
            "type": "text",
            "required": false
        },
        {
            "key": "disableUrl",
            "label": "Disable URL in Notification",
            "type": "boolean",
            "required": false
        },
        {
            "key": "discordSuppressNotifications",
            "label": "Suppress Notifications",
            "type": "boolean",
            "required": false
        }
    ],
    "egosms": [
        {
            "key": "egosmsUsername",
            "label": "here",
            "type": "text",
            "required": true
        },
        {
            "key": "egosmsPassword",
            "label": "Password",
            "type": "secret",
            "required": true
        },
        {
            "key": "egosmsSender",
            "label": "From Name/Number",
            "type": "text",
            "required": false
        },
        {
            "key": "egosmsPhoneNumber",
            "label": "Recipient Number",
            "type": "text",
            "required": true
        }
    ],
    "evolution": [
        {
            "key": "evolutionInstanceName",
            "label": "Instance Name",
            "type": "text",
            "required": true
        },
        {
            "key": "evolutionApiUrl",
            "label": "API URL",
            "type": "text",
            "required": false
        },
        {
            "key": "evolutionAuthToken",
            "label": "Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "evolutionRecipient",
            "label": "Phone Number / Contact ID / Group ID",
            "type": "text",
            "required": true
        },
        {
            "key": "evolutionUseCustomMessage",
            "label": "Custom Message (optional)",
            "type": "boolean",
            "required": false
        }
    ],
    "Feishu": [
        {
            "key": "feishuWebHookUrl",
            "label": "Feishu WebHookURL",
            "type": "text",
            "required": true
        }
    ],
    "FlashDuty": [
        {
            "key": "flashdutyIntegrationKey",
            "label": "Push URL",
            "type": "secret",
            "required": false
        },
        {
            "key": "flashdutySeverity",
            "label": "Severity",
            "type": "select",
            "required": true,
            "options": [
                "Info",
                "Warning",
                "Critical"
            ]
        }
    ],
    "Flowtriq": [
        {
            "key": "flowtriqWebhookUrl",
            "label": "Webhook URL",
            "type": "url",
            "required": true
        },
        {
            "key": "flowtriqApiKey",
            "label": "API Key",
            "type": "secret",
            "required": false
        }
    ],
    "fluxer": [
        {
            "key": "fluxerWebhookUrl",
            "label": "Fluxer Webhook URL",
            "type": "secret",
            "required": true
        },
        {
            "key": "fluxerUsername",
            "label": "Bot Display Name",
            "type": "text",
            "required": false
        },
        {
            "key": "fluxerPrefixMessage",
            "label": "Prefix Custom Message",
            "type": "text",
            "required": false
        },
        {
            "key": "fluxerMessageFormat",
            "label": "Message Format",
            "type": "select",
            "required": false,
            "options": [
                "normal",
                "minimalist",
                "custom"
            ]
        }
    ],
    "FreeMobile": [
        {
            "key": "freemobileUser",
            "label": "Free Mobile User Identifier",
            "type": "text",
            "required": true
        },
        {
            "key": "freemobilePass",
            "label": "Free Mobile API Key",
            "type": "text",
            "required": true
        }
    ],
    "GoAlert": [
        {
            "key": "goAlertBaseURL",
            "label": "Base URL",
            "type": "text",
            "required": true
        },
        {
            "key": "goAlertToken",
            "label": "Token",
            "type": "secret",
            "required": true
        }
    ],
    "gorush": [
        {
            "key": "gorushDeviceToken",
            "label": "Device Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "gorushServerURL",
            "label": "Server URL",
            "type": "text",
            "required": true
        },
        {
            "key": "gorushPlatform",
            "label": "Platform",
            "type": "select",
            "required": false,
            "options": [
                "ios",
                "android",
                "huawei"
            ]
        },
        {
            "key": "gorushTitle",
            "label": "Title",
            "type": "text",
            "required": false
        },
        {
            "key": "gorushPriority",
            "label": "Priority",
            "type": "select",
            "required": false,
            "options": [
                "normal",
                "high"
            ]
        },
        {
            "key": "gorushRetry",
            "label": "Retry",
            "type": "number",
            "required": false
        },
        {
            "key": "gorushTopic",
            "label": "Topic",
            "type": "text",
            "required": false
        }
    ],
    "gotify": [
        {
            "key": "gotifyapplicationToken",
            "label": "Application Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "gotifyserverurl",
            "label": "Server URL",
            "type": "text",
            "required": true
        },
        {
            "key": "gotifyPriority",
            "label": "Priority",
            "type": "number",
            "required": true
        }
    ],
    "HaloPSA": [
        {
            "key": "halowebhookurl",
            "label": "Halo PSA Webhook URL",
            "type": "secret",
            "required": true
        },
        {
            "key": "haloUsername",
            "label": "Username",
            "type": "text",
            "required": false
        },
        {
            "key": "haloPassword",
            "label": "Password",
            "type": "secret",
            "required": false
        }
    ],
    "Keep": [
        {
            "key": "webhookURL",
            "label": "Host URL",
            "type": "url",
            "required": true
        },
        {
            "key": "webhookAPIKey",
            "label": "API Key",
            "type": "secret",
            "required": true
        }
    ],
    "Kook": [
        {
            "key": "kookBotToken",
            "label": "Bot Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "kookGuildID",
            "label": "Guild ID",
            "type": "text",
            "required": true
        }
    ],
    "line": [
        {
            "key": "lineChannelAccessToken",
            "label": "Channel access token (Long-lived)",
            "type": "secret",
            "required": true
        },
        {
            "key": "lineUserID",
            "label": "Your user ID",
            "type": "text",
            "required": true
        }
    ],
    "lunasea": [
        {
            "key": "lunaseaTarget",
            "label": "Target",
            "type": "select",
            "required": true,
            "options": [
                "device",
                "user"
            ]
        },
        {
            "key": "lunaseaDevice",
            "label": "Device ID",
            "type": "text",
            "required": false
        },
        {
            "key": "lunaseaUserID",
            "label": "User ID",
            "type": "text",
            "required": false
        }
    ],
    "matrix": [
        {
            "key": "homeserverUrl",
            "label": "Homeserver URL (with http(s):// and optionally port)",
            "type": "text",
            "required": true
        },
        {
            "key": "internalRoomId",
            "label": "Internal Room ID",
            "type": "text",
            "required": true
        },
        {
            "key": "accessToken",
            "label": "Access Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "matrixUseTemplate",
            "label": "Use custom message template",
            "type": "boolean",
            "required": false
        }
    ],
    "mattermost": [
        {
            "key": "mattermostWebhookUrl",
            "label": "Webhook URL",
            "type": "text",
            "required": true
        },
        {
            "key": "mattermostusername",
            "label": "Username",
            "type": "text",
            "required": false
        },
        {
            "key": "mattermosticonurl",
            "label": "Icon URL",
            "type": "text",
            "required": false
        },
        {
            "key": "mattermosticonemo",
            "label": "Icon Emoji",
            "type": "text",
            "required": false
        },
        {
            "key": "mattermostchannel",
            "label": "Channel Name",
            "type": "text",
            "required": false
        }
    ],
    "max": [
        {
            "key": "maxBotToken",
            "label": "Bot Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "maxApiUrl",
            "label": "API URL",
            "type": "text",
            "required": true
        },
        {
            "key": "maxChatID",
            "label": "Chat ID",
            "type": "text",
            "required": true
        },
        {
            "key": "maxUseTemplate",
            "label": "Use custom message template",
            "type": "boolean",
            "required": false
        },
        {
            "key": "maxTemplateFormat",
            "label": "Message Format",
            "type": "select",
            "required": true,
            "options": [
                "plain",
                "markdown",
                "html"
            ]
        }
    ],
    "Milky": [
        {
            "key": "httpAddr",
            "label": "Milky HTTP Address(Without the '/api' suffix)",
            "type": "text",
            "required": true
        },
        {
            "key": "accessToken",
            "label": "Milky HTTP Address(Without the '/api' suffix)",
            "type": "secret",
            "required": true
        },
        {
            "key": "msgType",
            "label": "Milky Message Type",
            "type": "select",
            "required": false,
            "options": [
                "group",
                "private"
            ]
        },
        {
            "key": "recieverId",
            "label": "Group/User ID",
            "type": "text",
            "required": true
        }
    ],
    "nextcloudtalk": [
        {
            "key": "host",
            "label": "Nextcloud host",
            "type": "text",
            "required": false
        },
        {
            "key": "conversationToken",
            "label": "Conversation token",
            "type": "secret",
            "required": false
        },
        {
            "key": "botSecret",
            "label": "Bot secret",
            "type": "secret",
            "required": true
        },
        {
            "key": "sendSilentUp",
            "label": "Send UP silently",
            "type": "boolean",
            "required": false
        },
        {
            "key": "sendSilentDown",
            "label": "Send DOWN silently",
            "type": "boolean",
            "required": false
        }
    ],
    "nostr": [
        {
            "key": "relays",
            "label": "Nostr relays",
            "type": "text",
            "required": true
        },
        {
            "key": "sender",
            "label": "Sender Private Key (nsec)",
            "type": "secret",
            "required": true
        },
        {
            "key": "recipients",
            "label": "Recipients Public Keys (npub)",
            "type": "text",
            "required": true
        }
    ],
    "notifery": [
        {
            "key": "notiferyApiKey",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "notiferyTitle",
            "label": "Title",
            "type": "text",
            "required": false
        },
        {
            "key": "notiferyGroup",
            "label": "Group",
            "type": "text",
            "required": false
        }
    ],
    "ntfy": [
        {
            "key": "ntfytopic",
            "label": "ntfy Topic",
            "type": "text",
            "required": true
        },
        {
            "key": "ntfyserverurl",
            "label": "Server URL",
            "type": "text",
            "required": true
        },
        {
            "key": "ntfyPriority",
            "label": "Priority",
            "type": "number",
            "required": true
        },
        {
            "key": "ntfyPriorityDown",
            "label": "Priority for DOWN-events",
            "type": "number",
            "required": true
        },
        {
            "key": "ntfyAuthenticationMethod",
            "label": "Authentication Method",
            "type": "text",
            "required": false
        },
        {
            "key": "ntfyusername",
            "label": "Username",
            "type": "text",
            "required": false
        },
        {
            "key": "ntfypassword",
            "label": "Password",
            "type": "secret",
            "required": false
        },
        {
            "key": "ntfyaccesstoken",
            "label": "Access Token",
            "type": "secret",
            "required": false
        },
        {
            "key": "ntfyIcon",
            "label": "Icon URL",
            "type": "text",
            "required": false
        },
        {
            "key": "ntfyCall",
            "label": "Phone Call",
            "type": "text",
            "required": false
        },
        {
            "key": "ntfyUseTemplate",
            "label": "Customize notification templates",
            "type": "boolean",
            "required": false
        }
    ],
    "octopush": [
        {
            "key": "octopushVersion",
            "label": "Octopush API Version",
            "type": "select",
            "required": false,
            "options": [
                "2",
                "1"
            ]
        },
        {
            "key": "octopushAPIKey",
            "label": "\"API key\" from HTTP API credentials in control panel",
            "type": "secret",
            "required": true
        },
        {
            "key": "octopushLogin",
            "label": "\"Login\" from HTTP API credentials in control panel",
            "type": "text",
            "required": true
        },
        {
            "key": "octopushSMSType",
            "label": "SMS Type",
            "type": "select",
            "required": false,
            "options": [
                "sms_premium",
                "sms_low_cost"
            ]
        },
        {
            "key": "octopushPhoneNumber",
            "label": "Phone number (intl format, eg : +33612345678)",
            "type": "text",
            "required": true
        },
        {
            "key": "octopushSenderName",
            "label": "SMS Sender Name : 3-11 alphanumeric characters and space (a-zA-Z0-9)",
            "type": "text",
            "required": false
        }
    ],
    "OneBot": [
        {
            "key": "httpAddr",
            "label": "OneBot HTTP Address",
            "type": "text",
            "required": true
        },
        {
            "key": "accessToken",
            "label": "OneBot HTTP Address",
            "type": "secret",
            "required": true
        },
        {
            "key": "msgType",
            "label": "OneBot Message Type",
            "type": "select",
            "required": false,
            "options": [
                "group",
                "private"
            ]
        },
        {
            "key": "recieverId",
            "label": "Group/User ID",
            "type": "text",
            "required": true
        }
    ],
    "OneChat": [
        {
            "key": "accessToken",
            "label": "Access Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "recieverId",
            "label": "OneChat User ID or Group ID",
            "type": "text",
            "required": true
        },
        {
            "key": "botId",
            "label": "OneChat Bot ID",
            "type": "text",
            "required": true
        }
    ],
    "Onesender": [
        {
            "key": "onesenderURL",
            "label": "Host Onesender",
            "type": "url",
            "required": true
        },
        {
            "key": "onesenderToken",
            "label": "Token Onesender",
            "type": "secret",
            "required": true
        },
        {
            "key": "onesenderTypeReceiver",
            "label": "Recipient Type",
            "type": "select",
            "required": true,
            "options": [
                "private",
                "group"
            ]
        },
        {
            "key": "onesenderReceiver",
            "label": "Make sure the GroupID is valid. To send message into Group, ex: 628123456789-342345",
            "type": "text",
            "required": true
        }
    ],
    "Ooredoo": [
        {
            "key": "ooredooUsername",
            "label": "Username",
            "type": "text",
            "required": true
        },
        {
            "key": "ooredooAccessKey",
            "label": "Access Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "ooredooBearerToken",
            "label": "Bearer Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "ooredooToNumber",
            "label": "Recipient Number",
            "type": "text",
            "required": true
        },
        {
            "key": "ooredooServerUrl",
            "label": "API URL",
            "type": "text",
            "required": false
        }
    ],
    "openwa": [
        {
            "key": "openwaApiUrl",
            "label": "API URL",
            "type": "url",
            "required": true
        },
        {
            "key": "openwaApiKey",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "openwaSession",
            "label": "Session",
            "type": "text",
            "required": true
        },
        {
            "key": "openwaChatId",
            "label": "Chat ID (Phone Number / Contact ID / Group ID)",
            "type": "text",
            "required": true
        },
        {
            "key": "openwaUseCustomMessage",
            "label": "Custom Message (optional)",
            "type": "boolean",
            "required": false
        }
    ],
    "Opsgenie": [
        {
            "key": "opsgenieRegion",
            "label": "Region",
            "type": "select",
            "required": true,
            "options": [
                "us",
                "eu"
            ]
        },
        {
            "key": "opsgenieApiKey",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "opsgeniePriority",
            "label": "Priority",
            "type": "number",
            "required": false
        }
    ],
    "PagerDuty": [
        {
            "key": "pagerdutyIntegrationKey",
            "label": "Integration Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "pagerdutyIntegrationUrl",
            "label": "Integration URL",
            "type": "text",
            "required": false
        },
        {
            "key": "pagerdutyPriority",
            "label": "Priority",
            "type": "select",
            "required": false,
            "options": [
                "info",
                "warning",
                "error",
                "critical"
            ]
        },
        {
            "key": "pagerdutyAutoResolve",
            "label": "Auto resolve or acknowledged",
            "type": "select",
            "required": false,
            "options": [
                "0",
                "acknowledge",
                "resolve"
            ]
        }
    ],
    "PagerTree": [
        {
            "key": "pagertreeIntegrationUrl",
            "label": "Integration URL",
            "type": "text",
            "required": false
        },
        {
            "key": "pagertreeUrgency",
            "label": "Urgency",
            "type": "select",
            "required": false,
            "options": [
                "silent",
                "low",
                "medium",
                "high",
                "critical"
            ]
        },
        {
            "key": "pagertreeAutoResolve",
            "label": "Auto Resolve",
            "type": "select",
            "required": false,
            "options": [
                "resolve",
                "0"
            ]
        }
    ],
    "pinglet": [
        {
            "key": "pingletPublishUrl",
            "label": "Topic URL",
            "type": "url",
            "required": true
        },
        {
            "key": "pingletApiKey",
            "label": "API Key",
            "type": "secret",
            "required": true
        }
    ],
    "plivo": [
        {
            "key": "plivoAuthID",
            "label": "Auth ID",
            "type": "text",
            "required": true
        },
        {
            "key": "plivoAuthToken",
            "label": "Auth Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "plivoFromNumber",
            "label": "From Number",
            "type": "text",
            "required": true
        },
        {
            "key": "plivoToNumber",
            "label": "To Number",
            "type": "text",
            "required": true
        },
        {
            "key": "plivoMessageType",
            "label": "Message Type",
            "type": "select",
            "required": false,
            "options": [
                "sms",
                "call"
            ]
        },
        {
            "key": "plivoAnswerUrl",
            "label": "Answer URL",
            "type": "url",
            "required": true
        }
    ],
    "promosms": [
        {
            "key": "promosmsLogin",
            "label": "API Login Name",
            "type": "text",
            "required": true
        },
        {
            "key": "promosmsPassword",
            "label": "API Password",
            "type": "secret",
            "required": true
        },
        {
            "key": "promosmsSMSType",
            "label": "SMS Type",
            "type": "select",
            "required": false,
            "options": [
                "0",
                "1",
                "3",
                "4"
            ]
        },
        {
            "key": "promosmsPhoneNumber",
            "label": "Phone number (for Polish recipient You can skip area codes)",
            "type": "text",
            "required": true
        },
        {
            "key": "promosmsSenderName",
            "label": "SMS Sender Name : Pre-registred name or one of defaults: InfoSMS, SMS Info, MaxSMS, INFO, SMS",
            "type": "text",
            "required": false
        },
        {
            "key": "promosmsAllowLongSMS",
            "label": "Allow long SMS",
            "type": "boolean",
            "required": false
        }
    ],
    "pumble": [
        {
            "key": "webhookURL",
            "label": "Webhook URL",
            "type": "url",
            "required": true
        }
    ],
    "PushDeer": [
        {
            "key": "pushdeerServer",
            "label": "PushDeer Server URL",
            "type": "text",
            "required": false
        },
        {
            "key": "pushdeerKey",
            "label": "PushDeer Key",
            "type": "secret",
            "required": true
        }
    ],
    "PushPlus": [
        {
            "key": "pushPlusSendKey",
            "label": "SendKey",
            "type": "secret",
            "required": true
        }
    ],
    "pushbullet": [
        {
            "key": "pushbulletAccessToken",
            "label": "Access Token",
            "type": "secret",
            "required": true
        }
    ],
    "pushover": [
        {
            "key": "pushoveruserkey",
            "label": "User Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "pushoverapptoken",
            "label": "Application Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "pushoverdevice",
            "label": "Device",
            "type": "text",
            "required": false
        },
        {
            "key": "pushovertitle",
            "label": "Message Title",
            "type": "text",
            "required": false
        },
        {
            "key": "pushoverpriority",
            "label": "Priority",
            "type": "text",
            "required": false
        },
        {
            "key": "pushoversounds",
            "label": "Notification Sound",
            "type": "text",
            "required": false
        },
        {
            "key": "pushoversounds_up",
            "label": "Notification Sound",
            "type": "text",
            "required": false
        },
        {
            "key": "pushoverttl",
            "label": "Message TTL (Seconds)",
            "type": "number",
            "required": false
        }
    ],
    "pushy": [
        {
            "key": "pushyAPIKey",
            "label": "Secret API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "pushyToken",
            "label": "Device token",
            "type": "secret",
            "required": true
        }
    ],
    "Resend": [
        {
            "key": "resendApiKey",
            "label": "Resend API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "resendFromEmail",
            "label": "From Email",
            "type": "text",
            "required": true
        },
        {
            "key": "resendFromName",
            "label": "From Name",
            "type": "text",
            "required": false
        },
        {
            "key": "resendToEmail",
            "label": "To Email",
            "type": "text",
            "required": true
        },
        {
            "key": "resendSubject",
            "label": "Subject",
            "type": "text",
            "required": false
        }
    ],
    "SIGNL4": [
        {
            "key": "webhookURL",
            "label": "SIGNL4 Webhook URL",
            "type": "url",
            "required": true
        }
    ],
    "smsc": [
        {
            "key": "smscLogin",
            "label": "here",
            "type": "text",
            "required": true
        },
        {
            "key": "smscPassword",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "smscToNumber",
            "label": "Recipient Number",
            "type": "text",
            "required": true
        },
        {
            "key": "smscSenderName",
            "label": "From Name/Number",
            "type": "text",
            "required": false
        },
        {
            "key": "smscTranslit",
            "label": "smscTranslit",
            "type": "select",
            "required": false,
            "options": [
                "0",
                "1",
                "2"
            ]
        }
    ],
    "SMSEagle": [
        {
            "key": "smseagleUrl",
            "label": "Your SMSEagle device URL",
            "type": "text",
            "required": true
        },
        {
            "key": "smseagleToken",
            "label": "API Access token",
            "type": "secret",
            "required": true
        },
        {
            "key": "smseagleApiType",
            "label": "API version",
            "type": "select",
            "required": false,
            "options": [
                "smseagle-apiv1",
                "smseagle-apiv2"
            ]
        },
        {
            "key": "smseagleRecipientType",
            "label": "Recipient type",
            "type": "select",
            "required": false,
            "options": [
                "smseagle-to",
                "smseagle-group",
                "smseagle-contact"
            ]
        },
        {
            "key": "smseagleRecipient",
            "label": "Recipient(s) (multiple must be separated with comma)",
            "type": "text",
            "required": true
        },
        {
            "key": "smseaglePriority",
            "label": "Message priority (0-9, highest priority = 9)",
            "type": "number",
            "required": true
        },
        {
            "key": "smseagleEncoding",
            "label": "Message type",
            "type": "boolean",
            "required": false
        },
        {
            "key": "smseagleMsgType",
            "label": "Message type",
            "type": "select",
            "required": false,
            "options": [
                "smseagle-sms",
                "smseagle-ring",
                "smseagle-tts",
                "smseagle-tts-advanced"
            ]
        },
        {
            "key": "smseagleDuration",
            "label": "Duration (in seconds)",
            "type": "number",
            "required": false
        },
        {
            "key": "smseagleTtsModel",
            "label": "Text-to-speech model ID",
            "type": "number",
            "required": true
        },
        {
            "key": "smseagleRecipientTo",
            "label": "Phone number(s)",
            "type": "text",
            "required": false
        },
        {
            "key": "smseagleRecipientGroup",
            "label": "Phonebook group ID(s)",
            "type": "text",
            "required": false
        },
        {
            "key": "smseagleRecipientContact",
            "label": "Phonebook contact ID(s)",
            "type": "text",
            "required": false
        }
    ],
    "smsir": [
        {
            "key": "smsirApiKey",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "smsirNumber",
            "label": "Recipient Numbers",
            "type": "text",
            "required": true
        },
        {
            "key": "smsirTemplate",
            "label": "Template ID",
            "type": "text",
            "required": true
        }
    ],
    "SMSManager": [
        {
            "key": "smsmanagerApiKey",
            "label": "here",
            "type": "secret",
            "required": false
        },
        {
            "key": "numbers",
            "label": "Recipients",
            "type": "text",
            "required": false
        },
        {
            "key": "messageType",
            "label": "Gateway Type",
            "type": "select",
            "required": false,
            "options": [
                "economy",
                "lowcost",
                "high"
            ]
        }
    ],
    "SMSPartner": [
        {
            "key": "smspartnerApikey",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "smspartnerPhoneNumber",
            "label": "Phone number(s)",
            "type": "text",
            "required": true
        },
        {
            "key": "smspartnerSenderName",
            "label": "SMS Sender Name",
            "type": "text",
            "required": true
        }
    ],
    "smtp": [
        {
            "key": "smtpHost",
            "label": "Hostname",
            "type": "text",
            "required": true
        },
        {
            "key": "smtpPort",
            "label": "Port",
            "type": "number",
            "required": true
        },
        {
            "key": "smtpSecure",
            "label": "Security",
            "type": "select",
            "required": false,
            "options": [
                "false",
                "true"
            ]
        },
        {
            "key": "smtpIgnoreTLSError",
            "label": "Ignore TLS Error",
            "type": "boolean",
            "required": false
        },
        {
            "key": "smtpIgnoreSTARTTLS",
            "label": "Disable STARTTLS",
            "type": "boolean",
            "required": false
        },
        {
            "key": "smtpUsername",
            "label": "Username",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpPassword",
            "label": "Password",
            "type": "secret",
            "required": false
        },
        {
            "key": "smtpFrom",
            "label": "From Email",
            "type": "text",
            "required": true
        },
        {
            "key": "smtpTo",
            "label": "To Email",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpCC",
            "label": "CC",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpBCC",
            "label": "BCC",
            "type": "text",
            "required": false
        },
        {
            "key": "htmlBody",
            "label": "Use HTML for custom E-mail body",
            "type": "boolean",
            "required": false
        },
        {
            "key": "smtpAdditionalHeaders",
            "label": "documentation",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpDkimDomain",
            "label": "Domain Name",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpDkimKeySelector",
            "label": "Key Selector",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpDkimPrivateKey",
            "label": "Private Key",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpDkimHashAlgo",
            "label": "Hash Algorithm (Optional)",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpDkimheaderFieldNames",
            "label": "Header Keys to sign (Optional)",
            "type": "text",
            "required": false
        },
        {
            "key": "smtpDkimskipFields",
            "label": "Header Keys not to sign (Optional)",
            "type": "text",
            "required": false
        }
    ],
    "ServerChan": [
        {
            "key": "serverChanSendKey",
            "label": "SendKey",
            "type": "secret",
            "required": true
        }
    ],
    "serwersms": [
        {
            "key": "serwersmsUsername",
            "label": "API Username (incl. webapi_ prefix)",
            "type": "text",
            "required": true
        },
        {
            "key": "serwersmsPassword",
            "label": "API Password",
            "type": "secret",
            "required": true
        },
        {
            "key": "serwersmsRecipientType",
            "label": "Recipient type",
            "type": "select",
            "required": false,
            "options": [
                "phone",
                "group"
            ]
        },
        {
            "key": "serwersmsPhoneNumber",
            "label": "Phone number",
            "type": "text",
            "required": true
        },
        {
            "key": "serwersmsGroupId",
            "label": "Group ID",
            "type": "text",
            "required": true
        },
        {
            "key": "serwersmsSenderName",
            "label": "SMS Sender Name (registered via customer portal)",
            "type": "text",
            "required": false
        }
    ],
    "SevenIO": [
        {
            "key": "sevenioApiKey",
            "label": "SevenIO API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "sevenioSender",
            "label": "Sending number or name",
            "type": "text",
            "required": false
        },
        {
            "key": "sevenioReceiver",
            "label": "Receiving number",
            "type": "number",
            "required": true
        }
    ],
    "signal": [
        {
            "key": "signalURL",
            "label": "Post URL",
            "type": "url",
            "required": true
        },
        {
            "key": "signalNumber",
            "label": "Number",
            "type": "text",
            "required": true
        },
        {
            "key": "signalRecipients",
            "label": "Recipients",
            "type": "text",
            "required": true
        },
        {
            "key": "signalUseTemplate",
            "label": "Use custom message template",
            "type": "boolean",
            "required": false
        }
    ],
    "slack": [
        {
            "key": "slackwebhookURL",
            "label": "Webhook URL",
            "type": "text",
            "required": true
        },
        {
            "key": "slackusername",
            "label": "Username",
            "type": "text",
            "required": false
        },
        {
            "key": "slackiconemo",
            "label": "Icon Emoji",
            "type": "text",
            "required": false
        },
        {
            "key": "slackchannel",
            "label": "Channel Name",
            "type": "text",
            "required": false
        },
        {
            "key": "slackrichmessage",
            "label": "Send rich messages",
            "type": "boolean",
            "required": false
        },
        {
            "key": "slackIncludeGroupName",
            "label": "Include monitor group name",
            "type": "boolean",
            "required": false
        },
        {
            "key": "slackUseTemplate",
            "label": "Use custom message template",
            "type": "boolean",
            "required": false
        },
        {
            "key": "slackchannelnotify",
            "label": "Notify Channel",
            "type": "boolean",
            "required": false
        }
    ],
    "Splunk": [
        {
            "key": "splunkRestURL",
            "label": "Splunk Rest URL",
            "type": "secret",
            "required": true
        },
        {
            "key": "splunkSeverity",
            "label": "Severity",
            "type": "select",
            "required": false,
            "options": [
                "INFO",
                "WARNING",
                "CRITICAL"
            ]
        },
        {
            "key": "splunkAutoResolve",
            "label": "Auto resolve or acknowledged",
            "type": "select",
            "required": false,
            "options": [
                "0",
                "ACKNOWLEDGEMENT",
                "RECOVERY"
            ]
        }
    ],
    "SpugPush": [
        {
            "key": "templateKey",
            "label": "Template Code",
            "type": "secret",
            "required": true
        }
    ],
    "squadcast": [
        {
            "key": "squadcastWebhookURL",
            "label": "Post URL",
            "type": "url",
            "required": true
        }
    ],
    "stackfield": [
        {
            "key": "stackfieldwebhookURL",
            "label": "Webhook URL",
            "type": "text",
            "required": true
        }
    ],
    "teams": [
        {
            "key": "webhookUrl",
            "label": "Webhook URL",
            "type": "text",
            "required": true
        },
        {
            "key": "teamsEnableTags",
            "label": "Include tags",
            "type": "boolean",
            "required": false
        }
    ],
    "telegram": [
        {
            "key": "telegramBotToken",
            "label": "Bot Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "telegramChatID",
            "label": "Chat ID",
            "type": "text",
            "required": true
        },
        {
            "key": "telegramMessageThreadID",
            "label": "(Optional) Message Thread ID",
            "type": "text",
            "required": false
        },
        {
            "key": "telegramServerUrl",
            "label": "(Optional) Server Url",
            "type": "text",
            "required": false
        },
        {
            "key": "telegramUseTemplate",
            "label": "Use custom message template",
            "type": "boolean",
            "required": false
        },
        {
            "key": "telegramTemplateParseMode",
            "label": "Message Format",
            "type": "select",
            "required": true,
            "options": [
                "plain",
                "HTML",
                "MarkdownV2"
            ]
        },
        {
            "key": "telegramSendSilently",
            "label": "Send Silently",
            "type": "boolean",
            "required": false
        },
        {
            "key": "telegramProtectContent",
            "label": "Protect Forwarding/Saving",
            "type": "boolean",
            "required": false
        }
    ],
    "telnyx": [
        {
            "key": "telnyxApiKey",
            "label": "API Key (V2)",
            "type": "secret",
            "required": true
        },
        {
            "key": "telnyxPhoneNumber",
            "label": "From Number",
            "type": "text",
            "required": true
        },
        {
            "key": "telnyxToNumber",
            "label": "To Number",
            "type": "text",
            "required": true
        },
        {
            "key": "telnyxMessagingProfileId",
            "label": "Messaging Profile ID (optional)",
            "type": "text",
            "required": false
        }
    ],
    "Teltonika": [
        {
            "key": "teltonikaUrl",
            "label": "Your Teltonika device URL",
            "type": "url",
            "required": true
        },
        {
            "key": "teltonikaUnsafeTls",
            "label": "Ignore certificate validation",
            "type": "boolean",
            "required": false
        },
        {
            "key": "teltonikaUsername",
            "label": "API username",
            "type": "text",
            "required": true
        },
        {
            "key": "teltonikaPassword",
            "label": "API password",
            "type": "secret",
            "required": true
        },
        {
            "key": "teltonikaModem",
            "label": "Modem Id",
            "type": "text",
            "required": true
        },
        {
            "key": "teltonikaPhoneNumber",
            "label": "Phone number",
            "type": "text",
            "required": true
        }
    ],
    "threema": [
        {
            "key": "threemaRecipientType",
            "label": "Recipient Type",
            "type": "select",
            "required": true,
            "options": [
                "identity",
                "phone",
                "email"
            ]
        },
        {
            "key": "threemaRecipient",
            "label": "Threema-ID",
            "type": "text",
            "required": true
        },
        {
            "key": "threemaSenderIdentity",
            "label": "Gateway-ID",
            "type": "text",
            "required": true
        },
        {
            "key": "threemaSecret",
            "label": "Gateway-ID Secret",
            "type": "secret",
            "required": true
        }
    ],
    "TurboSMTP": [
        {
            "key": "turbosmtpConsumerKey",
            "label": "Consumer Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "turbosmtpConsumerSecret",
            "label": "Consumer Secret",
            "type": "secret",
            "required": true
        },
        {
            "key": "turbosmtpRegion",
            "label": "Region",
            "type": "select",
            "required": true,
            "options": [
                "us",
                "eu"
            ]
        },
        {
            "key": "turbosmtpFromEmail",
            "label": "From Email",
            "type": "text",
            "required": true
        },
        {
            "key": "turbosmtpToEmail",
            "label": "To Email",
            "type": "text",
            "required": true
        },
        {
            "key": "turbosmtpCcEmail",
            "label": "CC",
            "type": "text",
            "required": false
        },
        {
            "key": "turbosmtpBccEmail",
            "label": "BCC",
            "type": "text",
            "required": false
        },
        {
            "key": "turbosmtpSubject",
            "label": "Subject:",
            "type": "text",
            "required": false
        }
    ],
    "twilio": [
        {
            "key": "twilioAccountSID",
            "label": "Account SID",
            "type": "text",
            "required": true
        },
        {
            "key": "twilioApiKey",
            "label": "Api Key (optional)",
            "type": "secret",
            "required": false
        },
        {
            "key": "twilioMessagingServiceSID",
            "label": "Messaging Service SID (optional)",
            "type": "text",
            "required": false
        },
        {
            "key": "twilioAuthToken",
            "label": "Auth Token / Api Key Secret",
            "type": "secret",
            "required": true
        },
        {
            "key": "twilioFromNumber",
            "label": "From Number",
            "type": "text",
            "required": true
        },
        {
            "key": "twilioToNumber",
            "label": "To Number",
            "type": "text",
            "required": true
        }
    ],
    "VK": [
        {
            "key": "vkAccessToken",
            "label": "Access Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "vkApiVersion",
            "label": "API Version",
            "type": "text",
            "required": true
        },
        {
            "key": "vkPeerId",
            "label": "Peer ID",
            "type": "text",
            "required": true
        },
        {
            "key": "vkDontParseLinks",
            "label": "Disable link snippets",
            "type": "boolean",
            "required": false
        }
    ],
    "VKTeams": [
        {
            "key": "vkteamsBotToken",
            "label": "Bot Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "vkteamsChatId",
            "label": "Chat ID",
            "type": "text",
            "required": true
        },
        {
            "key": "vkteamsBaseUrl",
            "label": "API URL",
            "type": "text",
            "required": true
        },
        {
            "key": "vkteamsUseTemplate",
            "label": "Use custom message template",
            "type": "boolean",
            "required": false
        },
        {
            "key": "vkteamsTemplateFormat",
            "label": "Message Format",
            "type": "select",
            "required": true,
            "options": [
                "plain",
                "MarkdownV2",
                "HTML"
            ]
        }
    ],
    "waha": [
        {
            "key": "wahaApiUrl",
            "label": "API URL",
            "type": "url",
            "required": true
        },
        {
            "key": "wahaApiKey",
            "label": "API Key",
            "type": "secret",
            "required": false
        },
        {
            "key": "wahaSession",
            "label": "Session",
            "type": "text",
            "required": true
        },
        {
            "key": "wahaChatId",
            "label": "Chat ID (Phone Number / Contact ID / Group ID)",
            "type": "text",
            "required": true
        }
    ],
    "WPush": [
        {
            "key": "wpushAPIkey",
            "label": "API Key",
            "type": "secret",
            "required": true
        },
        {
            "key": "wpushChannel",
            "label": "API Key",
            "type": "select",
            "required": true,
            "options": [
                "wechat",
                "sms",
                "mail",
                "feishu",
                "dingtalk",
                "wechat_work"
            ]
        }
    ],
    "WeCom": [
        {
            "key": "weComBotKey",
            "label": "WeCom Bot Key",
            "type": "text",
            "required": true
        },
        {
            "key": "weComMentionedMobileList",
            "label": "WeCom Mentioned Mobile List",
            "type": "text",
            "required": false
        }
    ],
    "webhook": [
        {
            "key": "webhookURL",
            "label": "Post URL",
            "type": "url",
            "required": true
        },
        {
            "key": "httpMethod",
            "label": "HTTP Method",
            "type": "select",
            "required": false,
            "options": [
                "post",
                "get"
            ]
        },
        {
            "key": "webhookContentType",
            "label": "Request Body",
            "type": "select",
            "required": true,
            "options": [
                "json",
                "form-data",
                "custom"
            ]
        },
        {
            "key": "webhookAdditionalHeaders",
            "label": "Sets additional headers sent with the webhook. Each header should be defined as a JSON key/value.",
            "type": "text",
            "required": false
        }
    ],
    "whapi": [
        {
            "key": "whapiApiUrl",
            "label": "API URL",
            "type": "text",
            "required": false
        },
        {
            "key": "whapiAuthToken",
            "label": "Token",
            "type": "secret",
            "required": true
        },
        {
            "key": "whapiRecipient",
            "label": "Phone Number / Contact ID / Group ID",
            "type": "text",
            "required": true
        }
    ],
    "WxPusher": [
        {
            "key": "wxpusherSPT",
            "label": "S P T",
            "type": "secret",
            "required": true
        }
    ],
    "YZJ": [
        {
            "key": "yzjWebHookUrl",
            "label": "YZJ Webhook URL",
            "type": "url",
            "required": true
        },
        {
            "key": "yzjToken",
            "label": "YZJ Robot token",
            "type": "secret",
            "required": true
        }
    ]
};

module.exports = { NOTIFICATION_FIELDS };
