const FORMAT_NAME = "uptime-gizmo-configuration";
const FORMAT_VERSION = 1;

const LIMITS = Object.freeze({
    maxBytes: 128 * 1024 * 1024,
    maxDepth: 20,
    maxNodes: 2000000,
    maxRows: 100000,
    maxRowsPerResource: 50000,
    maxStringLength: 8 * 1024 * 1024,
});

const TABLE_REGISTRY = Object.freeze({
    docker_host: {
        category: "configuration",
        resource: "dockerHosts",
        ownerColumns: ["user_id"],
        columns: ["id", "user_id", "docker_daemon", "docker_type", "name"],
    },
    group: {
        category: "configuration",
        resource: "groups",
        columns: ["id", "name", "created_date", "public", "active", "weight", "status_page_id"],
        booleanColumns: ["public", "active"],
        references: { status_page_id: "statusPages" },
    },
    proxy: {
        category: "configuration",
        resource: "proxies",
        ownerColumns: ["user_id"],
        columns: [
            "id",
            "user_id",
            "protocol",
            "host",
            "port",
            "auth",
            "username",
            "password",
            "active",
            "default",
            "created_date",
        ],
        booleanColumns: ["auth", "active", "default"],
    },
    monitor: {
        category: "configuration",
        resource: "monitors",
        ownerColumns: ["user_id"],
        columns: [
            "id",
            "name",
            "active",
            "user_id",
            "interval",
            "url",
            "type",
            "weight",
            "hostname",
            "port",
            "created_date",
            "keyword",
            "maxretries",
            "ignore_tls",
            "upside_down",
            "maxredirects",
            "accepted_statuscodes_json",
            "dns_resolve_type",
            "dns_resolve_server",
            "dns_last_result",
            "retry_interval",
            "push_token",
            "method",
            "body",
            "headers",
            "basic_auth_user",
            "basic_auth_pass",
            "docker_host",
            "docker_container",
            "proxy_id",
            "expiry_notification",
            "mqtt_topic",
            "mqtt_success_message",
            "mqtt_username",
            "mqtt_password",
            "database_connection_string",
            "database_query",
            "auth_method",
            "auth_domain",
            "auth_workstation",
            "grpc_url",
            "grpc_protobuf",
            "grpc_body",
            "grpc_metadata",
            "grpc_method",
            "grpc_service_name",
            "grpc_enable_tls",
            "radius_username",
            "radius_password",
            "radius_calling_station_id",
            "radius_called_station_id",
            "radius_secret",
            "resend_interval",
            "packet_size",
            "game",
            "http_body_encoding",
            "description",
            "tls_ca",
            "tls_cert",
            "tls_key",
            "parent",
            "invert_keyword",
            "json_path",
            "expected_value",
            "kafka_producer_topic",
            "kafka_producer_brokers",
            "kafka_producer_ssl",
            "kafka_producer_allow_auto_topic_creation",
            "kafka_producer_sasl_options",
            "kafka_producer_message",
            "oauth_client_id",
            "oauth_client_secret",
            "oauth_token_url",
            "oauth_scopes",
            "oauth_auth_method",
            "timeout",
            "gamedig_given_port_only",
            "mqtt_check_type",
            "remote_browser",
            "snmp_oid",
            "snmp_version",
            "json_path_operator",
            "cache_bust",
            "conditions",
            "rabbitmq_nodes",
            "rabbitmq_username",
            "rabbitmq_password",
            "smtp_security",
            "ws_ignore_sec_websocket_accept_header",
            "ws_subprotocol",
            "ping_count",
            "ping_numeric",
            "ping_per_request_timeout",
            "ip_family",
            "manual_status",
            "oauth_audience",
            "mqtt_websocket_path",
            "domain_expiry_notification",
            "save_response",
            "save_error_response",
            "response_max_length",
            "system_service_name",
            "subtype",
            "location",
            "protocol",
            "snmp_v3_username",
            "expected_tls_alert",
            "retry_only_on_status_code_failure",
            "screenshot_delay",
            "ntp_stratum_threshold",
            "ntp_time_offset_threshold",
            "ntp_root_dispersion_threshold",
            "bearer_token",
            "gamedig_token",
            "web3_network_id",
            "web3_address",
            "web3_token_contract",
            "web3_token_decimals",
            "web3_min_balance",
            "web3_max_block_age",
            "web3_call_to",
            "web3_call_data",
            "web3_value_offset",
            "web3_value_type",
            "web3_value_decimals",
            "web3_value_operator",
            "web3_value_threshold",
            "web3_block_tag",
            "llm_model",
            "llm_api_key",
            "llm_prompt",
            "llm_max_tokens",
            "llm_max_latency",
            "external_ref",
            "llm_credential_id",
        ],
        booleanColumns: [
            "active",
            "ignore_tls",
            "upside_down",
            "expiry_notification",
            "grpc_enable_tls",
            "invert_keyword",
            "kafka_producer_ssl",
            "kafka_producer_allow_auto_topic_creation",
            "gamedig_given_port_only",
            "cache_bust",
            "ws_ignore_sec_websocket_accept_header",
            "ping_numeric",
            "domain_expiry_notification",
            "save_response",
            "save_error_response",
            "retry_only_on_status_code_failure",
        ],
        references: {
            parent: "monitors",
            docker_host: "dockerHosts",
            proxy_id: "proxies",
            remote_browser: "remoteBrowsers",
            web3_network_id: "web3Networks",
        },
    },
    incident: {
        category: "configuration",
        resource: "activeIncidents",
        columns: [
            "id",
            "title",
            "content",
            "style",
            "created_date",
            "last_updated_date",
            "pin",
            "active",
            "status_page_id",
        ],
        booleanColumns: ["pin", "active"],
        references: { status_page_id: "statusPages" },
        exportWhere: { active: 1 },
    },
    maintenance: {
        category: "configuration",
        resource: "maintenances",
        ownerColumns: ["user_id"],
        columns: [
            "id",
            "title",
            "description",
            "user_id",
            "active",
            "strategy",
            "start_date",
            "end_date",
            "start_time",
            "end_time",
            "weekdays",
            "days_of_month",
            "interval_day",
            "cron",
            "timezone",
            "duration",
            "last_start_date",
        ],
        booleanColumns: ["active"],
    },
    status_page: {
        category: "configuration",
        resource: "statusPages",
        columns: [
            "id",
            "slug",
            "title",
            "description",
            "icon",
            "theme",
            "published",
            "search_engine_index",
            "show_tags",
            "password",
            "created_date",
            "modified_date",
            "footer_text",
            "custom_css",
            "show_powered_by",
            "analytics_id",
            "show_certificate_expiry",
            "auto_refresh_interval",
            "analytics_script_url",
            "analytics_type",
            "show_only_last_heartbeat",
            "rss_title",
            "icon_size",
            "icon_position",
            "title_size",
            "title_font",
            "text_size",
        ],
        booleanColumns: [
            "published",
            "search_engine_index",
            "show_tags",
            "show_powered_by",
            "show_certificate_expiry",
            "show_only_last_heartbeat",
        ],
    },
    maintenance_status_page: {
        category: "configuration",
        resource: "maintenanceStatusPages",
        columns: ["id", "status_page_id", "maintenance_id"],
        references: { status_page_id: "statusPages", maintenance_id: "maintenances" },
    },
    monitor_group: {
        category: "configuration",
        resource: "monitorGroups",
        columns: ["id", "monitor_id", "group_id", "weight", "send_url", "custom_url"],
        booleanColumns: ["send_url"],
        references: { monitor_id: "monitors", group_id: "groups" },
    },
    monitor_maintenance: {
        category: "configuration",
        resource: "monitorMaintenances",
        columns: ["id", "monitor_id", "maintenance_id"],
        references: { monitor_id: "monitors", maintenance_id: "maintenances" },
    },
    notification: {
        category: "configuration",
        resource: "notifications",
        ownerColumns: ["user_id"],
        columns: ["id", "name", "active", "user_id", "is_default", "config"],
        booleanColumns: ["active", "is_default"],
    },
    monitor_notification: {
        category: "configuration",
        resource: "monitorNotifications",
        columns: ["id", "monitor_id", "notification_id"],
        references: { monitor_id: "monitors", notification_id: "notifications" },
    },
    tag: {
        category: "configuration",
        resource: "tags",
        columns: ["id", "name", "color", "created_date"],
    },
    monitor_tag: {
        category: "configuration",
        resource: "monitorTags",
        columns: ["id", "monitor_id", "tag_id", "value"],
        references: { monitor_id: "monitors", tag_id: "tags" },
    },
    status_page_cname: {
        category: "configuration",
        resource: "statusPageCnames",
        columns: ["id", "status_page_id", "domain"],
        references: { status_page_id: "statusPages" },
    },
    remote_browser: {
        category: "configuration",
        resource: "remoteBrowsers",
        ownerColumns: ["user_id"],
        columns: ["id", "name", "url", "user_id"],
    },
    web3_network: {
        category: "configuration",
        resource: "web3Networks",
        ownerColumns: ["user_id"],
        columns: ["id", "user_id", "name", "chain_id", "rpc_url", "active", "created_date"],
        booleanColumns: ["active"],
    },
    setting: {
        category: "settings",
        columns: ["id", "key", "value", "type"],
    },
    user: { category: "identity" },
    api_key: { category: "identity" },
    heartbeat: { category: "history" },
    stat_minutely: { category: "history" },
    stat_hourly: { category: "history" },
    stat_daily: { category: "history" },
    monitor_tls_info: { category: "derived" },
    domain_expiry: { category: "derived" },
    notification_sent_history: { category: "history" },
    maintenance_timeslot: { category: "derived", optional: true },
    knex_migrations: { category: "internal" },
    knex_migrations_lock: { category: "internal" },
    sqlite_sequence: { category: "internal", optional: true },
});

const SETTING_REGISTRY = Object.freeze({
    apiKeysEnabled: { category: "identity", reason: "Target API access policy" },
    checkBeta: { category: "configuration" },
    checkUpdate: { category: "configuration" },
    chromeExecutable: { category: "host", reason: "Target filesystem path" },
    cloudflaredTunnelToken: { category: "configuration", type: null },
    configurationImportAppliedDigest: { category: "internal", reason: "Import commit marker" },
    customThemes: { category: "configuration" },
    databasePatchedFiles: { category: "internal", reason: "Migration bookkeeping" },
    database_version: { category: "internal", reason: "Migration bookkeeping" },
    description: { category: "configuration", legacy: true },
    disableAuth: { category: "identity", reason: "Target authentication policy" },
    domainExpiryNotifyDays: { category: "configuration" },
    entryPage: { category: "configuration" },
    globalpingApiToken: { category: "configuration" },
    icon: { category: "configuration", legacy: true },
    initServerTimezone: { category: "internal", reason: "Startup migration marker" },
    instanceOwnerId: { category: "identity", reason: "Target estate owner" },
    jwtSecret: { category: "identity", reason: "Target session signing key" },
    keepDataPeriodDays: { category: "configuration" },
    llmActiveCredentialId: { category: "configuration" },
    llmApiKey: { category: "configuration", legacy: true },
    llmBaseUrl: { category: "configuration", legacy: true },
    llmCredentials: { category: "configuration" },
    llmModel: { category: "configuration", legacy: true },
    llmProvider: { category: "configuration", legacy: true },
    migrateAggregateTableState: { category: "internal", reason: "Migration bookkeeping" },
    nscd: { category: "host", reason: "Target container service setting" },
    primaryBaseURL: { category: "configuration" },
    rdapDnsData: { category: "derived", reason: "Cached RDAP bootstrap data" },
    searchEngineIndex: { category: "configuration", legacy: true },
    serverTimezone: { category: "configuration" },
    statusPagePublished: { category: "configuration", legacy: true },
    statusPageTags: { category: "configuration", legacy: true },
    statusPageTheme: { category: "configuration", legacy: true },
    steamAPIKey: { category: "configuration" },
    title: { category: "configuration", legacy: true },
    tlsExpiryNotifyDays: { category: "configuration" },
    trustProxy: { category: "host", reason: "Target reverse-proxy trust boundary" },
    webpushPrivateVapidKey: { category: "identity", reason: "Target Web Push application identity" },
    webpushPublicVapidKey: { category: "identity", reason: "Target Web Push application identity" },
});

const CONFIGURATION_TABLES = Object.freeze(
    Object.entries(TABLE_REGISTRY)
        .filter(([, entry]) => entry.category === "configuration")
        .map(([table]) => table)
);

const RESOURCE_NAMES = Object.freeze(CONFIGURATION_TABLES.map((table) => TABLE_REGISTRY[table].resource));

const INSERT_ORDER = Object.freeze([
    "docker_host",
    "proxy",
    "remote_browser",
    "web3_network",
    "notification",
    "tag",
    "status_page",
    "maintenance",
    "monitor",
    "group",
    "incident",
    "maintenance_status_page",
    "monitor_group",
    "monitor_maintenance",
    "monitor_notification",
    "monitor_tag",
    "status_page_cname",
]);

const DELETE_ORDER = Object.freeze([...INSERT_ORDER].reverse());

const HISTORY_TABLES = Object.freeze([
    "notification_sent_history",
    "domain_expiry",
    "monitor_tls_info",
    "stat_daily",
    "stat_hourly",
    "stat_minutely",
    "heartbeat",
    "maintenance_timeslot",
]);

const PORTABLE_SETTING_KEYS = Object.freeze(
    Object.entries(SETTING_REGISTRY)
        .filter(([, entry]) => entry.category === "configuration")
        .map(([key]) => key)
        .sort()
);

module.exports = {
    CONFIGURATION_TABLES,
    DELETE_ORDER,
    FORMAT_NAME,
    FORMAT_VERSION,
    HISTORY_TABLES,
    INSERT_ORDER,
    LIMITS,
    PORTABLE_SETTING_KEYS,
    RESOURCE_NAMES,
    SETTING_REGISTRY,
    TABLE_REGISTRY,
};
